[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/about"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/podcast"
  to = "/podcast/"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/contact/"
  status = 301

[[redirects]]
  from = "/truths"
  to = "/truths/"
  status = 301

[[redirects]]
  from = "/playbook"
  to = "/playbook/"
  status = 301

[[redirects]]
  from = "/partner"
  to = "/partner.html"
  status = 200

[[headers]]
  for = "/partner*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"

[[headers]]
  for = "/netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
